spring:
  kafka:
    bootstrap-servers: 192.168.99.101:9092

app:
  topic:
    message: clientmessage.t

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.memorynotfound: DEBUG
    o.a.k.clients.consumer.ConsumerConfig: WARN